# Generated by Django 3.2.3 on 2021-05-19 21:07

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField()),
                ('slug', models.SlugField()),
                ('featured', models.BooleanField(default=False)),
                ('live_site', models.URLField(max_length=300)),
                ('git_repo', models.URLField(max_length=500)),
                ('project_detail', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
